"""
AI Activity Recommendation models
REQ-016: AI reads onboarding profile → generates activity recommendations
REQ-017: Caregiver views recommendations per elderly
REQ-018: Approve → auto-create schedule entry
"""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database.base import Base
from src.database.enums import ActivityCategory, RecommendationStatus


class AIActivityRecommendation(Base):
    """
    Generated by the AI service using the elderly's profile data:
    - age, mobility_level, physical_condition
    - medical_history (to exclude contraindicated activities)
    - hobbies_interests (to align with existing interests)
    - recent health trends (optional enrichment)

    Status flow:
        pending → approved  (service creates Schedule, sets approved_by/approved_at)
        pending → rejected  (dismissed by caregiver)

    ai_reasoning stores the LLM's explanation for why this activity
    is appropriate — shown to caregiver for transparency.
    """

    __tablename__ = "ai_activity_recommendations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    elderly_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("elderly_profiles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Activity data ─────────────────────────────────────────────────────────
    activity_name: Mapped[str] = mapped_column(String(255), nullable=False)
    category: Mapped[ActivityCategory] = mapped_column(String(30), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    duration_minutes: Mapped[Optional[int]] = mapped_column(nullable=True)
    frequency_suggestion: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True  # e.g. "3x per week", "daily"
    )

    # ── AI metadata ───────────────────────────────────────────────────────────
    ai_reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    ai_model_version: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    ai_prompt_version: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True  # track which prompt template generated this
    )

    # ── Approval lifecycle (REQ-018) ──────────────────────────────────────────
    status: Mapped[RecommendationStatus] = mapped_column(
        String(20), nullable=False, default=RecommendationStatus.PENDING, index=True
    )
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    approved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    rejection_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=func.now()
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    elderly: Mapped["ElderlyProfile"] = relationship(  # noqa: F821
        back_populates="ai_recommendations", lazy="select"
    )
    approver: Mapped[Optional["User"]] = relationship(  # noqa: F821
        foreign_keys=[approved_by], lazy="select"
    )
    # Reverse link — set after approval creates a Schedule
    schedule: Mapped[Optional["Schedule"]] = relationship(  # noqa: F821
        back_populates="ai_recommendation",
        foreign_keys="Schedule.ai_recommendation_id",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<AIActivityRecommendation id={self.id} activity={self.activity_name} status={self.status}>"
