"""create_all_tables

Revision ID: b3e1ee4b8fd1
Revises: 001_fuzzy_health
Create Date: 2026-05-03 21:23:46.342744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e1ee4b8fd1'
down_revision: Union[str, None] = '001_fuzzy_health'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health_records', 'cholesterol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='mg/dL — metabolic module',
               existing_nullable=True)
    op.alter_column('health_records', 'uric_acid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='mg/dL — metabolic module',
               existing_nullable=True)
    op.alter_column('health_records', 'spo2_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='% — cardiovascular & infection modules',
               existing_nullable=True)
    op.alter_column('health_records', 'cardio_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Fuzzy cardiovascular score 0-100',
               existing_nullable=True)
    op.alter_column('health_records', 'metabolic_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Fuzzy metabolic score 0-100',
               existing_nullable=True)
    op.alter_column('health_records', 'infection_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Fuzzy infection score 0-100',
               existing_nullable=True)
    op.alter_column('health_records', 'fuzzy_final_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Fuzzy final averaged score 0-100',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health_records', 'fuzzy_final_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Fuzzy final averaged score 0-100',
               existing_nullable=True)
    op.alter_column('health_records', 'infection_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Fuzzy infection score 0-100',
               existing_nullable=True)
    op.alter_column('health_records', 'metabolic_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Fuzzy metabolic score 0-100',
               existing_nullable=True)
    op.alter_column('health_records', 'cardio_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Fuzzy cardiovascular score 0-100',
               existing_nullable=True)
    op.alter_column('health_records', 'spo2_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='% — cardiovascular & infection modules',
               existing_nullable=True)
    op.alter_column('health_records', 'uric_acid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='mg/dL — metabolic module',
               existing_nullable=True)
    op.alter_column('health_records', 'cholesterol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='mg/dL — metabolic module',
               existing_nullable=True)
    # ### end Alembic commands ###
